databases:
  - name: wwjnpatz
    databaseName: wwjnpatz
    user: wwjnpatz

services:
  - type: web
    name: best_recipe_app_ever
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wwjnpatz
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false